CREATE TABLE sys.`MEMBER` (
	ID VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(256) NULL,
	NAME VARCHAR(50) NULL,
	BIRTH_DAY VARCHAR(8) NULL,
	PHONE VARCHAR(11) NULL,
	GENDER VARCHAR(1) NULL,
	REG_DT DATETIME NULL,
	REGISTRAR VARCHAR(20) NULL,
	MODIFY_DT DATETIME NULL,
	MODIFIER VARCHAR(20) NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;