CREATE TABLE `USER` (
	UID INT UNSIGNED NOT NULL COMMENT 'UID' AUTO_INCREMENT,
	EMAIL VARCHAR(20) NOT NULL COMMENT '이메일',
	PASSWORD VARCHAR(256) NOT NULL COMMENT '비밀번호',
	NAME VARCHAR(50) NOT NULL COMMENT '이름',
	BIRTH_DAY VARCHAR(8) NOT NULL COMMENT '생년월일(YYYYMMDD)',
	PHONE VARCHAR(11) NOT NULL COMMENT '전화번호(01039741139)',
	GENDER VARCHAR(1) NOT NULL COMMENT '성별(M,F)',
	REG_DT DATETIME NULL COMMENT '등록일시',
	REGISTRAR VARCHAR(20) NULL COMMENT '등록자',
	MODIFY_DT DATETIME NULL COMMENT '수정일시',
	MODIFIER VARCHAR(20) NULL COMMENT '수정자',
	CONSTRAINT USER_PK PRIMARY KEY (UID),
	CONSTRAINT CK_GENDER CHECK(GENDER IN ('M', 'F'))
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;

CREATE TABLE `AUTHORITY` (
	UID INT UNSIGNED NOT NULL COMMENT 'UID' AUTO_INCREMENT,
	CODE VARCHAR(2) NOT NULL COMMENT '코드',
	NAME VARCHAR(50) NOT NULL COMMENT '이름',
	DESCRIPTION VARCHAR(200) NOT NULL COMMENT '설명',
	REG_DT DATETIME NULL COMMENT '등록일시',
	REGISTRAR VARCHAR(20) NULL COMMENT '등록자',
	MODIFY_DT DATETIME NULL COMMENT '수정일시',
	MODIFIER VARCHAR(20) NULL COMMENT '수정자',
	CONSTRAINT AUTHORITY_PK PRIMARY KEY (UID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ROLE` (
	UID INT UNSIGNED NOT NULL COMMENT 'UID' AUTO_INCREMENT,
	USER_UID INT UNSIGNED NOT NULL COMMENT '아이디',
	AUTHORITY_UID INT UNSIGNED NOT NULL COMMENT '코드',
	REG_DT DATETIME NULL COMMENT '등록일시',
	REGISTRAR VARCHAR(20) NULL COMMENT '등록자',
	MODIFY_DT DATETIME NULL COMMENT '수정일시',
	MODIFIER VARCHAR(20) NULL COMMENT '수정자',
	CONSTRAINT ROLE_PK PRIMARY KEY (UID),
	FOREIGN KEY (`USER_UID`) REFERENCES `USER` (`UID`),
	FOREIGN KEY (`AUTHORITY_UID`) REFERENCES `AUTHORITY` (`UID`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;

CREATE TABLE `DEPARTMENT` (
	UID INT UNSIGNED NOT NULL COMMENT 'UID' AUTO_INCREMENT,
	CODE VARCHAR(3) NOT NULL COMMENT '코드',
	PARENT_UID INT UNSIGNED NULL COMMENT '상위 코드',
	NAME VARCHAR(20) NOT NULL COMMENT '이름',
	DESCRIPTION VARCHAR(50) NULL COMMENT '설명',
	REG_DT DATETIME NULL COMMENT '등록일시',
	REGISTRAR VARCHAR(20) NULL COMMENT '등록자',
	MODIFY_DT DATETIME NULL COMMENT '수정일시',
	MODIFIER VARCHAR(20) NULL COMMENT '수정자',
	CONSTRAINT DEPARTMENT_PK PRIMARY KEY (UID),
	FOREIGN KEY (PARENT_UID) REFERENCES `DEPARTMENT` (`UID`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;